sylius_grid:
    grids:
        app_admin_sponsor:
            driver:
                name: doctrine/orm
                options:
                    class: '%app.model.sponsor.class%'
            fields:
                code:
                    type: string
                    label: app.ui.code
                    sortable: ~
                name:
                    type: string
                    label: app.ui.name
                    sortable: ~
                tier:
                    type: string
                    label: app.ui.tier
                    sortable: ~
            actions:
                main:
                    create:
                        type: create
                        label: app.ui.create
                items:
                    delete:
                        type: delete
                        label: app.ui.delete
                    update:
                        type: update
                        label: app.ui.update
                        
